// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF39CEDUbNQi5JLdxSVkKERye1bNgwhOI',
    appId: '1:348365535897:web:73446cef9657b38f5b5608',
    messagingSenderId: '348365535897',
    projectId: 'kotsukotsushare',
    authDomain: 'kotsukotsushare.firebaseapp.com',
    storageBucket: 'kotsukotsushare.appspot.com',
    measurementId: 'G-7PRK6353PT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjAbduE4io_Bw3T63PD1DuDsmkAUeaTxM',
    appId: '1:205923031060:android:93083707079f278132ef01',
    messagingSenderId: '205923031060',
    projectId: 'chokushii-1ecc5',
    storageBucket: 'chokushii-1ecc5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpJwwbBbdtaGN3i997DE0da2KrtbieGnw',
    appId: '1:205923031060:ios:e24955005d483bb932ef01',
    messagingSenderId: '205923031060',
    projectId: 'chokushii-1ecc5',
    storageBucket: 'chokushii-1ecc5.appspot.com',
    iosBundleId: 'com.tomurango.chokushii',
  );

}