// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF39CEDUbNQi5JLdxSVkKERye1bNgwhOI',
    appId: '1:348365535897:web:73446cef9657b38f5b5608',
    messagingSenderId: '348365535897',
    projectId: 'kotsukotsushare',
    authDomain: 'kotsukotsushare.firebaseapp.com',
    storageBucket: 'kotsukotsushare.appspot.com',
    measurementId: 'G-7PRK6353PT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmpbOzLrfs9eS4rwc0F4ueadLwAa2RL9g',
    appId: '1:348365535897:android:6176bc7590e860835b5608',
    messagingSenderId: '348365535897',
    projectId: 'kotsukotsushare',
    storageBucket: 'kotsukotsushare.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAaoEtxqTfdGrLp1PnyQYpAYNbpTTznr0',
    appId: '1:348365535897:ios:e30ef5e3f9d350a95b5608',
    messagingSenderId: '348365535897',
    projectId: 'kotsukotsushare',
    storageBucket: 'kotsukotsushare.appspot.com',
    iosBundleId: 'com.example.kotsukotsushareApp',
  );
}
